version: "3.9"

services:
  app:
    image: python:3.11-slim
    container_name: eg_app
    working_dir: /app
    volumes:
      - ./app:/app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && bash start.sh"
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DSN: postgresql://postgres:postgres@postgres:5432/shop
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      RUN_ETL: "1"
    depends_on:
      - postgres
      - neo4j

  neo4j:
    image: neo4j:5.20
    container_name: eg_neo4j
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc","graph-data-science"]'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*,gds.*"
    ports:
      - "7474:7474"   # HTTP browser
      - "7687:7687"   # Bolt protocol
    volumes:
      - neo4jdata:/data
      - ./neo4j/import:/import

  postgres:
    image: postgres:16
    container_name: eg_postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  neo4jdata: